name: A Basic Workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the world
        run: echo "Hello from our first job!"
      - name: Checkout repository code
        uses: actions/checkout@v4
